// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "termlnk-react-native-russh.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RusshSpec.h"

@interface ReactNativeRussh : NSObject <NativeReactNativeRusshSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ReactNativeRussh : NSObject <RCTBridgeModule>
#endif

@end