// Generated by uniffi-bindgen-react-native
#include "termlnk-react-native-russh.h"
#include "generated/uniffi_russh.hpp"

namespace termlnk_reactnativerussh {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeUniffiRussh::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}