#ifndef TERMLNK_REACTNATIVERUSSH_H
#define TERMLNK_REACTNATIVERUSSH_H
// Generated by uniffi-bindgen-react-native
#include <cstdint>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvoker.h>

namespace termlnk_reactnativerussh {
  using namespace facebook;

  uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker);
  uint8_t cleanupRustCrate(jsi::Runtime &runtime);
}

#endif /* TERMLNK_REACTNATIVERUSSH_H */