// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "termlnk-react-native-russh.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// Automated testing checks Java_com_termlnk_russh_ReactNativeRusshModule and termlnk_reactnativerussh
// by comparing the whole line here.
/*
Java_com_termlnk_russh_ReactNativeRusshModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return termlnk_reactnativerussh::multiply(a, b);
}
*/

// Installer coming from ReactNativeRusshModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_com_termlnk_russh_ReactNativeRusshModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    using JCallInvokerHolder = facebook::react::CallInvokerHolder;

    auto holderLocal = facebook::jni::make_local(callInvokerHolderJavaObj);
    auto holderRef = facebook::jni::static_ref_cast<JCallInvokerHolder::javaobject>(holderLocal);
    auto* holderCxx = holderRef->cthis();
    auto jsCallInvoker = holderCxx->getCallInvoker();
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);

    return termlnk_reactnativerussh::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_termlnk_russh_ReactNativeRusshModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return termlnk_reactnativerussh::cleanupRustCrate(*runtime);
}